#!/bin/sh

export LSCOLORS=Bxfxcxdxcxegedabagacad
export SHELL=/bin/zsh
export EDITOR="vim"
# source scripts/mvn_color.sh

alias l='ls -1'
alias untar="tar zxvf $@"
alias find_broken='find -L . -type l -ls'
alias mux=tmuxinator
alias mv='mv -i'

xmlify() {
    cat $1 | xmllint --format -
}

ppath() {
    for i in $(echo $PATH | tr ":" "\n")
    do
        print $i
    done
}

bak() {
    cp $1 "$1.bak"
}
