#!/bin/sh

export LSCOLORS=Bxfxcxdxcxegedabagacad
export SHELL=/bin/zsh
export EDITOR="vim"

alias untar="tar zxvf $@"

xmlify() {
    cat $1 | xmllint --format -
}

shrink() {
    sips --getProperty pixelWidth --getProperty pixelHeight  $1
    sips --resampleHeightWidth 566 800 -s format png screen_shot.tiff --out $2
}
